name: px
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.7
  - nodejs=10.*
  - bwa
  - samtools
  - bedtools
  - ucsc-bedtobigbed
  - ucsc-fetchchromsizes
  - deeptools
  - cython
  - cytoolz
  - scikit-learn=0.22.0
  - umap-learn
  - keras==2.2.5
  - seaborn
  - flask
  - flask-cors
  - pandas
  - pywget
  - bokeh
  - pydot
  - h5py
  # We need the next line only because of a weird bug. This can probably be
  # removed in the future: https://stackoverflow.com/a/52598942/981933
  - testpath==0.4.2
  - tqdm
  - matplotlib
  - requests
  - tsfresh
  - tslearn
  - statsmodels
  - pip
  - pip:
      - apricot-select
      - cooler
      - pysam==0.15.3
      - hgtiles==0.2.17
      - higlass-python==0.2.1
      - hnswlib==0.3.4
      - ipywidgets==7.5.1
      - joblib==0.14.0
      - jupyterlab==1.1.1
      - negspy
      - numba
      - pybbi
      - pytest==5.3.1
      - keras-tqdm
      - forestci
      - fastdtw
      - stringcase
